# Inheritance
# inherit_from:
#   - .rubocop_todo.yml
# Extensions
require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "config.ru"
    - "Rakefile"
    - "db/**/*"
    - "config/**/*"
    - "bin/{bundle,rails,rake,setup,update}"
    - !ruby/regexp /old_and_unused\.rb$/
    - "spec/spec_helper.rb"
    - "spec/dummy/**/*"
    - "vendor/**/*"
# Lint/UselessAssignment:
#   Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

# RSpec/BeforeAfterAll:
#   Enabled: false

# RSpec/ExampleLength:
#   Enabled: false

# RSpec/NestedGroups:
#   Max: 4

# Style/ClassAndModuleChildren:
#   Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
