image: docker:stable

pipelines:
  branches:
    development:
      - step:
          script:
            # Install bash & docker-compose
            - apk add --no-cache py-pip bash
            - pip install --no-cache-dir docker-compose
            - docker-compose -v
            # Build docker test image
            - docker-compose build --build-arg BUNDLE_WITHOUT=production --build-arg RAILS_ENV=test
            # Code analysis
            - docker-compose run app rubocop -d
            # Unit testing
            - docker-compose run app rspec -v="$BITBUCKET_CLONE_DIR:/app" -d
          services:
            - docker
          caches:
            - docker
