image: docker:stable

pipelines:
  branches:
    development:
      - step:
          script:
            # Install bash & docker-compose
            - apk add --no-cache py-pip bash
            - pip install --no-cache-dir docker-compose
            - docker-compose -v
            # Build docker test image
            - docker-compose build --build-arg RAILS_ENV=test
            # Prepare DB image
            - docker-compose run db -v="$BITBUCKET_CLONE_DIR:/var/lib/postgresql/data"
            # Code analysis
            - docker-compose run app rubocop
            # Unit testing
            - docker-compose run app rspec
          services:
            - docker
          caches:
            - docker
