version: "3.7"

services:
  db:
    image: postgres:10.9-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=authenticator
  app:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=
        - RAILS_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    entrypoint: "./docker-entrypoint.sh"
    environment:
      - DB_HOST=db

volumes:
  db-data:
