version: '3'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=condovive
      - POSTGRES_DB=authenticator
  app:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=
        - RAILS_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - COMPOSE_PROJECT_NAME=authenticator

volumes:
  db-data:
