version: '3'

services:
  db:
    image: postgres:10.5-alpine
    # persist db data with volume
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-net
    environment:
      - POSTGRES_USER=condovive
      - POSTGRES_DB=authenticator
  app:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=production
        - RAILS_ENV=test
    networks:
      - backend-net
    depends_on:
      - db
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file: .env
    environment:
      - DB_HOST=db

# persist data on volumes
volumes:
  db-data:

networks:
  backend-net:
    driver: bridge