version: '3'
services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=condovive
      - POSTGRES_DB=authenticator
  app:
    build:
      context: .
      args:
        - BUNDLE_WITHOUT=
        - RAILS_ENV=development
    entrypoint: docker/entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env
    environment:
      - DB_HOST=db
    tty: true
    stdin_open: true
volumes:
  db-data: