version: 2 # use CircleCI 2.0
jobs:
  build:
    branches:
      only:
        - development
    machine: true
    working_directory: ~/app
    steps:
      - checkout # special step to check out source code to working directory
      # - setup_remote_docker
      - run:
          name: Build project
          command: docker-compose up --build
      - run:
          name: Code analysis with Rubocop
          command: docker-compose exec app rubocop
      - run:
          name: Unit testing with RSpec
          command: |
            docker-compose exec app \
            rspec --profile 10 \
                  --format RspecJunitFormatter \
                  --out test_results/rspec.xml \
                  --format progress \
                  $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Save test results for timing analysis
      - store_test_results:
          path: test_results
