version: 2 # use CircleCI 2.0
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: docker/compose:1.22.0
    working_directory: ~/app
    environment:
      RAILS_ENV: test
      TEST_FILE: docker-compose.test.yml
    steps:
      - checkout # special step to check out source code to working directory
      - setup_remote_docker # configured to execute docker commands
      # Docker layer caching workaround
      - restore_cache:
          keys:
            - v1-docker-layers-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            if [ -f /caches/${CIRCLE_PROJECT_REPONAME}.tar.gz ]; then gunzip \
              -c /caches/${CIRCLE_PROJECT_REPONAME}.tar.gz | \
              docker load; docker images; fi
      - run:
          name: Build docker image & run containers
          command: |
            docker-compose -f $TEST_FILE -p ${CIRCLE_PROJECT_REPONAME} \
              up --build -d
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker build --tag ${CIRCLE_PROJECT_REPONAME} . | \
              grep '\-\-\->' | \
              grep -v 'Using cache' | \
              sed -e 's/[ >-]//g' > /tmp/layers.txt
            docker save $(cat /tmp/layers.txt) | \
              gzip > /caches/${CIRCLE_PROJECT_REPONAME}.tar.gz
      - save_cache:
          key: v1-docker-layers-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/
      # Tests
      - run:
          name: Code analysis with Rubocop
          command: |
            docker-compose -f $TEST_FILE exec app rubocop
      - run:
          name: Unit testing with RSpec
          command: |
            docker-compose -f $TEST_FILE exec app \
              rspec --profile 10 \
                    --format RspecJunitFormatter \
                    --out test_results/rspec.xml \
                    --format progress \
                    $(circleci tests glob "spec/**/*_spec.rb" | \
                      circleci tests split --split-by=timings)
            mkdir -p test_results
            docker-compose -f $TEST_FILE exec app \
              cat test_results/rspec.xml > test_results/rspec.xml
      - store_test_results:
          path: test_results
      # Artifacts
      - store_artifacts:
          path: test_results
