version: 2 # use CircleCI 2.0
jobs:
  build:
    branches:
      only:
        - development
    docker:
      - image: docker/compose:1.22.0
    working_directory: ~/app
    environment:
    steps:
      - checkout # special step to check out source code to working directory
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker-compose -f docker-compose.test.yml up --build -d
      - run:
          name: Code analysis with Rubocop
          command: |
            docker-compose -f docker-compose.test.yml exec app rubocop
      - run: mkdir -p test_results
      - run:
          name: Unit testing with RSpec
          command: |
            docker-compose -f docker-compose.test.yml exec app \
              rspec --profile 10 \
                    --format RspecJunitFormatter \
                    --out test_results/rspec.xml \
                    --format progress \
                    $(circleci tests glob "spec/**/*_spec.rb" | \
                      circleci tests split --split-by=timings)
            docker-compose -f docker-compose.test.yml exec app \
              cat test_results/rspec.xml > test_results/rspec.xml
      # # Save test results for timing analysis
      # - store_test_results:
      #     path: test_results
